version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - '.:/var/www/html'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-match_candy}
      - DB_USERNAME=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASS:-root}
  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-match_candy}
      - MYSQL_USER=${DB_USER:root}
      - MYSQL_PASSWORD=${DB_PASS:root}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:root}
    
